datacenter/datacenter/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^datafinder/', include('datafinder.urls', namespace='datafinder')),
]

datacenter/datafinder/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from datafinder import views


# from . import views

urlpatterns = (
    # urls for datafinder app
    url(r'^searchquery-list/$', login_required(views.Search_QueryListView.as_view()), name='search_query_list'),
    url(r'^searchquery-list/create/$', login_required(views.Search_QueryCreateView.as_view()), name='search_querycreateview'),
    url(r'^searchquery-list/update/(?P<pk>\S+)/$', login_required(views.Search_QueryUpdateView.as_view()), name='search_queryupdateview'),

    url(r'^resturant-list/$', login_required(views.RestaurantListView.as_view()), name='restaurantlistView'),
    url(r'^resturant-list/create$', login_required(views.RestaurantCreateView.as_view()), name='restaurantcreateview'),
    url(r'^resturant-list/update/(?P<pk>\S+)/', login_required(views.RestaurantUpdateView.as_view()), name='restaurantupdateview'),

    url(r'^apiprovider/$', login_required(views.APiProviderListView.as_view()), name='restfinder_apiprovider_list'),
    url(r'^apiprovider/create/$', login_required(views.APiProviderCreateView.as_view()), name='restfinder_apiprovider_create'),
    url(r'^apiprovider/detail/(?P<pk>\S+)/', login_required(views.APiProviderDetailView.as_view()), name='restfinder_apiprovider_detail'),
    url(r'^apiprovider/update/(?P<pk>\S+)/$', login_required(views.APiProviderUpdateView.as_view()), name='restfinder_apiprovider_update'),
    )

datacenter/datafinder/models.py
from django.db import models as models
from enumfields import EnumField
from django.shortcuts import reverse
from datafinder.enum import ApiProviderType

class Search_Query(models.Model):
    search = models.CharField(max_length=255)
    location = models.CharField(max_length=1000)
    radius = models.FloatField(max_length=1000)
    completed = models.BooleanField(blank=True, default=False) #what if this is null=True
    failed = models.BooleanField(blank=False, default=False)#what if this is null=True
    created_on = models.DateField(auto_now_add=True, blank=False)
    api_provider = EnumField(ApiProviderType)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.search

    def get_absolute_url(self):
        return reverse('datafinder:search_query_list')

    def get_update_url(self):
        return reverse('datafinder:search_queryupdateview', args=(self.pk,))


class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    unique_id = models.CharField(max_length=255, unique=True)
    phone = models.CharField(max_length=200, null=True)
    location = models.CharField(max_length=1000)
    categories = models.CharField(max_length=1000, null=True)
    website = models.URLField(max_length=255, null=True)
    lat = models.DecimalField(decimal_places=15, max_digits=50, null=True)
    lng = models.DecimalField(decimal_places=15, max_digits=50, null=True)
    cuisines = models.CharField(max_length=1000, null=True)
    yellowPagesData = models.CharField(max_length=1000, null=True)
    yelpData = models.CharField(max_length=1000, null=True)
    googleDataInfo = models.CharField(max_length=1000, null=True)
    zohoCrmId = models.CharField(max_length=1000, null=True)
    lastUpdated = models.DateField(auto_now=True)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('datafinder:restaurantlistView')

class APiProvider(models.Model):

    # Fields
    provider = EnumField(ApiProviderType)
    key = models.CharField(max_length=255)
    secret = models.CharField(max_length=255, blank=True)
    daily_limit = models.PositiveIntegerField(editable=False, default=995)

    class Meta:
        ordering = ('-pk',)


    def get_absolute_url(self):
        return reverse('datafinder:restfinder_apiprovider_detail', args=(self.pk,))


    # def get_update_url(self):
    #     return reverse('restfinder_apiprovider_update', args=(self.pk,))

datacenter/fetcher/models.py
from django.db import models

# Create your models here.

datacenter/datafinder/forms.py
from django import forms
# from .models import Search_Query, Restaurant, APiProvider
from datafinder.models import Restaurant, Search_Query, APiProvider


class Search_QueryForm(forms.ModelForm):
    class Meta:
        model = Search_Query
        fields = ['search', 'location', 'radius', 'api_provider']


class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'phone','lat','lng','location', 'categories', 'website', 'cuisines', 'yellowPagesData',
                  'yelpData', 'googleDataInfo']


class APiProviderForm(forms.ModelForm):
    class Meta:
        model = APiProvider
        fields = ['provider', 'key', 'secret']

datacenter/datafinder/views.py
from django.views.generic import DetailView, ListView, UpdateView, CreateView

from datafinder.forms import RestaurantForm, Search_QueryForm, APiProviderForm
from datafinder.models import Restaurant, Search_Query, APiProvider

# from .models import Search_Query, Restaurant
# from .forms import Search_QueryForm, RestaurantForm


class Search_QueryListView(ListView):
    model = Search_Query
    # x = list(Search_Query.objects.all().filter(completed=False).values_list('location', flat=True))
    # print(x)

class Search_QueryCreateView(CreateView):
    model = Search_Query
    form_class = Search_QueryForm


class Search_QueryDetailView(DetailView):
    model = Search_Query


class Search_QueryUpdateView(UpdateView):
    model = Search_Query
    form_class = Search_QueryForm


class RestaurantListView(ListView):
    model = Restaurant


class RestaurantCreateView(CreateView):
    model = Restaurant
    form_class = RestaurantForm


class RestaurantDetailView(DetailView):
    model = Restaurant


class RestaurantUpdateView(UpdateView):
    model = Restaurant
    form_class = RestaurantForm

class APiProviderListView(ListView):
    model = APiProvider

class APiProviderCreateView(CreateView):
    model = APiProvider
    form_class = APiProviderForm

class APiProviderDetailView(DetailView):
    model = APiProvider

class APiProviderUpdateView(UpdateView):
    model = APiProvider
    form_class = APiProviderForm

        # Resturaunt.objects.all().filter(completed='').value_lists('search_query')

datacenter/fetcher/views.py
from django.shortcuts import render

# Create your views here.

datacenter/datafinder/templates/base.html
<html><head></head><body>{% block content %}Replace this.{% endblock %}</body>

datacenter/datafinder/templates/datafinder/apiprovider_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'datafinder:restfinder_apiprovider_list' %}">APiProvider Listing</a></p>
<table class="table">
<tr><td>provider</td><td>{{ object.provider }}</td></tr>
<tr><td>key</td><td>{{ object.key }}</td></tr>
<tr><td>secret</td><td>{{ object.secret }}</td></tr>
<tr><td>daily_limit</td><td>{{ object.daily_limit }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit APiProvider</a>

{% endblock %}

datacenter/datafinder/templates/datafinder/apiprovider_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'datafinder:restfinder_apiprovider_list' %}">APiProvider Listing</a></p>
<form method="post">
{% csrf_token %}
{{form}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

datacenter/datafinder/templates/datafinder/apiprovider_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'datafinder:restfinder_apiprovider_list' %}">APiProvider Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>provider</td>
    <td>key</td>
    <td>secret</td>
    <td>daily_limit</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.provider }}</td>
    <td>{{ object.key }}</td>
    <td>{{ object.secret }}</td>
    <td>{{ object.daily_limit }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'datafinder:restfinder_apiprovider_create' %}">Create new APiProvider</a>
{% endblock %}

datacenter/datafinder/templates/datafinder/restaurant_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'vega_promptcloud_restaurant_list' %}">Restaurant Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>address</td><td>{{ object.address }}</td></tr>
<tr><td>phone</td><td>{{ object.phone }}</td></tr>
<tr><td>location</td><td>{{ object.location }}</td></tr>
<tr><td>categories</td><td>{{ object.categories }}</td></tr>
<tr><td>website</td><td>{{ object.website }}</td></tr>
<tr><td>cuisines</td><td>{{ object.cuisines }}</td></tr>
<tr><td>yellowPagesData</td><td>{{ object.yellowPagesData }}</td></tr>
<tr><td>yelpData</td><td>{{ object.yelpData }}</td></tr>
<tr><td>googleDataInfo</td><td>{{ object.googleDataInfo }}</td></tr>
<tr><td>lastUpdated</td><td>{{ object.lastUpdated }}</td></tr>
<tr><td>lastUploaded</td><td>{{ object.lastUploaded }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Restaurant</a>

{% endblock %}

datacenter/datafinder/templates/datafinder/restaurant_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<a class="btn btn-default" href="{% url 'datafinder:restaurantlistView' %}">Restaurant list</a>
<form method="post">
{% csrf_token %}
{{form}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

datacenter/datafinder/templates/datafinder/restaurant_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<a class="btn btn-default" href="{% url 'datafinder:restaurantcreateview' %}">Add new Restaurant</a>
<table class="table">
<tr>
    <td>Name</td>
    <td>Phone</td>
    <td>Location</td>
    <td>Map</td>
    <td>Categories</td>
    <td>Website</td>
    <td>Cuisines</td>
    <td>YellowPagesData</td>
    <td>YelpData</td>
    <td>GoogleDataInfo</td>
    <td>ZohoCrmId</td>
    <td>LastUpdated</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{ object.name }}</td>
    <td>{{ object.phone }}</td>
    <td>{{ object.location }}</td>
    <td><a href="http://maps.google.com/?q={{ object.lat }},{{ object.lat }}">Map</a></td>
    <td>{{ object.categories }}</td>
    <td>{{ object.website }}</td>
    <td>{{ object.cuisines }}</td>
    <td>{{ object.yellowPagesData }}</td>
    <td>{{ object.yelpData }}</td>
    <td>{{ object.googleDataInfo }}</td>
    <td>{{ object.zohoCrmId }}</td>
    <td>{{ object.lastUpdated }}</td>
</tr>
{% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/resturant-list?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/resturant-list?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</table>

{% endblock %}

datacenter/datafinder/templates/datafinder/search_query_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="#">Search_Query Listing</a></p>
<table class="table">
<tr><td>search</td><td>{{ object.search }}</td></tr>
<tr><td>location</td><td>{{ object.location }}</td></tr>
<tr><td>yelp</td><td>{{ object.yelp }}</td></tr>
<tr><td>yellow_pages</td><td>{{ object.yellow_pages }}</td></tr>
<tr><td>completed</td><td>{{ object.completed }}</td></tr>
<tr><td>failed</td><td>{{ object.failed }}</td></tr>
<tr><td>created_on</td><td>{{ object.created_on }}</td></tr>
<tr><td>google</td><td>{{ object.google }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Search_Query</a>

{% endblock %}

datacenter/datafinder/templates/datafinder/search_query_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<a class="btn btn-default" href="{% url 'datafinder:search_query_list' %}">Search_Query List</a>
<form method="post">
{% csrf_token %}
{{form}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

datacenter/datafinder/templates/datafinder/search_query_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<a class="btn btn-default" href="{% url 'datafinder:search_querycreateview' %}">Add Search Query</a>
<table class="table">
<tr>
    <td>Search</td>
    <td>Location</td>
    <td>Api_provider</td>
    <td>Radius</td>
    <td>Completed</td>
    <td>Failed</td>
    <td>Created_on</td>
    <td>UpdateInfo</td>


</tr>
{% for object in object_list %}
<tr>

    <td>{{ object.search }}</td>
    <td>{{ object.location }}</td>
    <td>{{ object.api_provider }}</td>
    <td>{{ object.radius }}</td>
    <td>{{ object.completed }}</td>
    <td>{{ object.failed }}</td>
{#    {% if object.completed %}#}
{#        <td>{{ object.completed }}</td>#}
{#    {% endif %}#}
{#    <td>{{ object.failed }}</td>#}
    <td><a class="btn btn-default" href="{{ object.get_update_url }}">Update</a></td>
    <!--{{ object.get_update_url }}-->
</tr>
{% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/searchquery-list?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/searchquery-list?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</table>

{% endblock %}